const T = {
  en: {
    // nav
    nav_home: "home", nav_work: "some work", nav_about: "about me",

    // home
    home_eyebrow: "Product Designer &nbsp;·&nbsp; Santiago, Chile",
    home_title: "I craft innovative &amp; disruptive creations",
    home_tags: "#ServiceDesign &nbsp;·&nbsp; #DataScience &nbsp;·&nbsp; #Automatization &nbsp;·&nbsp; #ChangeManagement",

    // about
    about_heading: "about me",
    about_origin: "Chilean · From the Andes Mountains",
    about_p1: `I'm a Senior Product Designer with a holistic approach that connects user experience (UX) with technical feasibility and business objectives. With a strong track record of transforming complex problems into scalable digital solutions, my strengths lie in data-driven design, innovation workshop facilitation, and end-to-end product vision.`,
    about_p2: `Unlike a traditional designer, I integrate development and product architecture knowledge to ensure every pixel designed is implementable and generates real impact. Expert in leading Discovery processes, creating design systems, and optimizing conversion flows. I've worked with global teams (such as at Globant) helping companies mature their design culture and accelerate their innovation cycles.`,
    contact_title: "Contact me",
    contact_write: "Write me!",
    contact_linkedin: "Visit my LinkedIn",
    contact_article: "Read my article on Medium",

    // work
    work_heading: "my work",
    work_cat1: "Health",
    work_title1: "Market fit for Ecgo, a new cardiac health device",
    work_tags1: "#UX research &nbsp;·&nbsp; #TechDriven &nbsp;·&nbsp; #DataScience &nbsp;·&nbsp; #Telemedicine",
    work_cat2: "Retail",
    work_title2: "Service Design case: Users at the Core of Automation",
    work_tags2: "#ServiceDesign &nbsp;·&nbsp; #DataScience &nbsp;·&nbsp; #Automatization",
    work_cat3: "Events",
    work_title3: "Internalize an external product: How does the UX/UI adapt?",
    work_tags3: "#UI &nbsp;·&nbsp; #DesignSystem &nbsp;·&nbsp; #Collaboration",

    // ecgo
    ecgo_cat: "Health",
    ecgo_title: "Market fit for Ecgo, a new cardiac health device",
    ecgo_date: "Ecgo &nbsp;·&nbsp; Health Tech &nbsp;·&nbsp; 2018–2019",
    ecgo_tags: "#UX Research &nbsp;·&nbsp; #TechDriven &nbsp;·&nbsp; #DataScience &nbsp;·&nbsp; #Telemedicine &nbsp;·&nbsp; #PublicHealth &nbsp;·&nbsp; #Startup",
    ecgo_req_h: "A device without software.",
    ecgo_req_p: "Ecgo had developed a new cardiac Holter sensor — but had no digital product around it. I was brought in to understand patients, doctors, and medical technicians deeply enough to design software from scratch that could work in hospitals, clinics, and patients' homes.",
    ecgo_disc_h: "Discovery",
    ecgo_s1: "Objective", ecgo_s2: "Planning", ecgo_s3: "Conducting", ecgo_s4: "Concluding", ecgo_s5: "Implementing",
    ecgo_field_label: "Field Research",
    ecgo_obj_h: "01 / Objective",
    ecgo_obj_p: "Our objective as the Solunova team was to understand all actors and their context of usage of a Holter cardiac exam in public health institutions.",
    ecgo_rq_label: "Research Questions",
    ecgo_q1: "How does the traditional cardiac Holter flow work?",
    ecgo_q2: "Who is part of this flow, what characterizes them?",
    ecgo_q3: "What is the minimum service (SAL) that is necessary to be implemented correctly?",
    ecgo_q4: "What are the challenges and opportunities of implementing software for patients?",
    ecgo_plan_label: "The Plan",
    ecgo_plan_h: "02 / Planning",
    ecgo_plan_p1: "My research approach was qualitative, with the commercial side completing the findings by using market, data-driven information.",
    ecgo_plan_p2: "This qualitative approach was based off of two research activities: non-participant observation sessions and unstructured interviews.",
    ecgo_part_h: "Participants",
    ecgo_part1: "4 patients", ecgo_part2: "2 medical technicians", ecgo_part3: "2 cardiac medical specialists",
    ecgo_cond_h: "03 / Conducting",
    ecgo_cond_p: "I conducted non-participant observations and in-depth interviews across three key user groups — in hospitals, clinics, and patients' homes.",
    ecgo_u1_title: "Cardiologists",
    ecgo_u1_desc: "Experts who shaped the cardiac exam report — defining the data quality doctors need to make clinical decisions.",
    ecgo_u2_title: "Medical Technicians",
    ecgo_u2_desc: "Key to understanding how cardiac signals travel from the device to the cardiologist — the critical handoff point.",
    ecgo_u3_title: "Patients",
    ecgo_u3_desc: "Segmented by age, tech comfort, and experience with the Holter process — the widest range of needs on the journey.",
    ecgo_obs_label: "Field Observation",
    ecgo_obs_text: "Non-participant observation carried out in 2-hour sessions at three institutions — tracking the full Holter exam flow firsthand.",
    ecgo_obs_loc: "Vival Medical Center &nbsp;·&nbsp; Kaplan Cardiac Foundation &nbsp;·&nbsp; Hospital Cordillera Oriente",
    ecgo_conc_h: "04 / Concluding",
    ecgo_conc_p: "Our research validated the device's potential — and gave us the foundation to design a completely new kind of cardiac monitoring service.",
    ecgo_days_unit: "Days",
    ecgo_days_desc: "Continuous cardiac monitoring — 4× longer than the traditional Holter exam.",
    ecgo_find_label: "Key Finding",
    ecgo_find_desc: "Detected cardiac conditions the traditional 24-hour Holter exam missed entirely.",
    ecgo_out_label: "Key Output",
    ecgo_out_desc: "Co-designed the clinical report and Service Level Agreement alongside the cardiologist and data scientist.",
    ecgo_impl_label: "What We Built",
    ecgo_impl_h: "05 / Implementing",
    ecgo_impl_c1_h: "Dashboard for Cardiologists",
    ecgo_impl_c1_p: "Add and register medical supervisors, patients, studies (reports), real-time exams, and new devices. Works for desktop and tablet.",
    ecgo_impl_c2_h: "APP for Patients",
    ecgo_impl_c2_p: "Users can input symptoms and log activity during their heart exam. Real-time data complements the cardiac signal monitoring.",
    ecgo_showcase_title: "The product we built",
    ecgo_impact_h: "Real impact",
    ecgo_impact_p: "The implementation was carried out through laboratory test demos, generating real medical exams with continued iterations until a stable version was reached. Design was key — considering accessibility for patients and adequate visualization of reports for cardiologists.",
    ecgo_still_label: "Still In Use",
    ecgo_still_note: "Implemented at the Kaplan Foundation.",
    footer_back: "← Back to work",
    footer_next: "Next project →",
    footer_prev: "← Previous project",
    footer_back2: "Back to work",

    // cencosud
    cen_cat: "Retail",
    cen_title: "Redesigning price management — users at the core of automation",
    cen_tags: "#ServiceDesign &nbsp;·&nbsp; #TechDriven &nbsp;·&nbsp; #DataScience &nbsp;·&nbsp; #Automatization &nbsp;·&nbsp; #ChangeManagement",
    cen_prob_label: "The Challenge",
    cen_prob_h: `Thousands of price changes. Hundreds of stores. Three teams that never "talked" to each other.`,
    cen_prob_sub: "The complexity wasn't just technical — it was organizational, cultural, and deeply human.",
    cen_brief_h: "A retailer flying blind.",
    cen_brief_p: "One of Latin America's largest retailers — 500+ stores, thousands of weekly price changes — running its entire pricing operation through spreadsheets, WhatsApp, and gut feel. My job was to change that.",
    cen_role: "My role: UX Designer &nbsp;·&nbsp; Service Design &nbsp;·&nbsp; Product Design",
    cen_scale_d1: "stores impacted", cen_scale_d2: "user types, distinct needs", cen_scale_d3: "products designed from scratch",
    cen_users_h: "Who I designed for",
    cen_u1_name: "Planners",
    cen_u1_desc: "Simulate price scenarios and plan weekly changes across product categories.",
    cen_u2_name: "Product Managers",
    cen_u2_desc: "Own product strategy and collections. Need full visibility across the pricing pipeline.",
    cen_u3_name: "Store Assistants",
    cen_u3_desc: "Apply price changes on the floor in real time — thousands of products, same day.",
    cen_field_label: "The Foundation",
    cen_field_h: "I went to the stores. No assumptions.",
    cen_field_p: "While everyone was debating features, I was in the stores watching what actually happened when a price change arrived. The gap between the system and reality was larger than anyone admitted.",
    cen_sm_label: "The Methodology",
    cen_sm_h: "How I Mapped the Problem",
    cen_sm_p: "Before designing a single screen, I mapped every step, every role, and every handoff in the price change chain. Eight activities. Five user types. Dozens of failure points. This map became the strategic foundation for every decision we made.",
    cen_sm_flow: "Product Manager &nbsp;→&nbsp; Planner &nbsp;→&nbsp; Category Manager &nbsp;→&nbsp; Price Analyst &nbsp;→&nbsp; Store Assistant",
    cen_a1: "Monitor Performance", cen_a2: "Flag Slow Products", cen_a3: "Suggest Optimal Price", cen_a4: "Configure Changes",
    cen_a5: "Update POS System", cen_a6: "Notify Category Team", cen_a7: "Alert Store Teams", cen_a8: "Label at Shelf",
    cen_stats1: "5 User Roles", cen_stats2: "8 Key Activities", cen_stats3: "15+ Features Designed",
    cen_orc_label: "My Key Contribution",
    cen_orc_h: "I mapped every role, dependency and failure point — then designed the orchestrator that made the whole system work.",
    cen_orc_p: "The orchestrator is a semi-automated workflow tool that tracks the maturity level of each week's pricing process against predefined time limits — alerting on errors and keeping all stakeholders in sync.",
    cen_prod_h: "Two products delivered*",
    cen_p1_name: "Back-Office Dashboard",
    cen_p1_desc: "End-to-end planning tool for Planners and PMs to simulate price scenarios, forecast revenue impact, and manage weekly pricing decisions.",
    cen_p1_tags: "Price simulation &nbsp;·&nbsp; Revenue forecasting &nbsp;·&nbsp; Weekly planning &nbsp;·&nbsp; Error tracking",
    cen_p2_name: "Store App &amp; Dashboard",
    cen_p2_desc: "Simple, fast tool for store staff to receive weekly price updates, log implementation, and upload photo proof — all in one place.",
    cen_p2_tags: "Real-time updates &nbsp;·&nbsp; Photo proof &nbsp;·&nbsp; Implementation log &nbsp;·&nbsp; Store dashboard",
    cen_disclaimer: "*design reference for confidentiality",

    // cvent
    cve_cat: "Events",
    cve_title: "Internalize an external product: How does the UX/UI adapt?",
    cve_ctx_label: "The Context",
    cve_ctx_h: "Studio. Acquired,<br>but not yet integrated.",
    cve_ctx_p1: "The Virtual Event Platform is a company providing software solutions focused on event management. Studio — a product acquired by the Platform — is an audiovisual production tool designed to optimize virtual and hybrid events through video conferencing.",
    cve_ctx_p2: "My main challenge was ensuring Studio became an integral part of the Virtual Event Platform experience — fluid and without interruptions for both attendees and event organizers.",
    cve_ch_h: "Studio Challenges",
    cve_ch1_name: "Old Legacy Design System", cve_ch1_sub: "without design system updates",
    cve_ch1_desc: "Structural deficiencies, outdated standards, and failed integrations made Studio's path into the Platform a significant obstacle.",
    cve_ch2_name: "Technological Limitation", cve_ch2_sub: "accessibility compliance at integration",
    cve_ch2_desc: "Polymer components didn't align with behavior, look, or accessibility standards — making a direct integration technically impossible.",
    cve_ap_h: "How did I approach it?",
    cve_ap1_name: "Audit our features and components",
    cve_ap1_desc: "Identify and prioritize essential components within the Studio experience.",
    cve_ap2_name: "Reverse engineering",
    cve_ap2_desc: "Understand the construction of components — states, structure, and behavior.",
    cve_ap3_name: "Design &amp; iteration",
    cve_ap3_desc: "Apply atomic design to rebuild components consistently and accessibly, aligned with the Platform's standards.",
    cve_ap4_name: "Publication",
    cve_ap4_desc: "Advocate the library to product and dev teams with documentation, cheat sheets, and business impact.",
    cve_aud_label: "The Audit",
    cve_aud_h: "1 / Audit our features<br>and components",
    cve_aud_p: "We couldn't rebuild everything — so we mapped what existed, removed redundancy, and ranked by impact.",
    cve_aud_l1: "→&nbsp; Cataloged all existing components",
    cve_aud_l2: "→&nbsp; Prioritized by usage and accessibility gap",
    cve_aud_l3: "→&nbsp; Flagged inconsistencies for rebuild",
    cve_scope_label: "Audit Scope",
    cve_scope_desc: "components mapped and prioritized",
    cve_scope_cats: "Navigation &nbsp;·&nbsp; Forms &nbsp;·&nbsp; Media<br>Overlays &nbsp;·&nbsp; Data Display &nbsp;·&nbsp; Utilities",
    cve_rev_h: "2 / Reverse engineering",
    cve_rev_p1: "The investigation focused on understanding the construction of Carina's components. These were highly intricate, requiring significant design and development resources, and designed for use cases that often differed from Studio's limited set.",
    cve_rev_p2: "This phase concluded with a comprehensive understanding of how UI, states, content, and accessibility were structured and functioned within Carina's components.",
    cve_rev_cap: "Component States &nbsp;·&nbsp; Actual Artifact",
    cve_des_label: "The Design",
    cve_des_h: "3 / Design &amp; iteration",
    cve_des_p: "Atomic design was the foundation — every component had defined states, behaviors, and accessibility built in from the first iteration.",
    cve_des_l1: "→&nbsp; Atoms to templates — full hierarchy",
    cve_des_l2: "→&nbsp; Unified Figma library across teams",
    cve_des_l3: "→&nbsp; Nomenclature agreed with design leads",
    cve_atomic_label: "Atomic Design Structure",
    cve_out_label: "The Outcome",
    cve_pub_h: "4 / Publication<br>and communication",
    cve_pub_quote: "\"Design was key — not just the components, but the shared language to talk about them.\"",
    cve_pub_body: "We advocated across product and engineering — creating documentation, cheat sheets, and a business case to transition to actual coding.",
    cve_del_label: "Delivered",
    cve_del_list: "· Intermediate component library<br>· Nomenclature documentation<br>· Accessibility standards guide<br>· Carina alignment cheat sheet",
  },

  es: {
    nav_home: "Inicio", nav_work: "Trabajos", nav_about: "Sobre mí",

    home_eyebrow: "Diseñadora de Producto &nbsp;·&nbsp; Santiago, Chile",
    home_title: "Creo productos innovadores y disruptivos",
    home_tags: "#DiseñoDeServicio &nbsp;·&nbsp; #CienciaDeDatos &nbsp;·&nbsp; #Automatización &nbsp;·&nbsp; #GestiónDelCambio",

    about_heading: "sobre mí",
    about_origin: "Chilena · De la Cordillera de los Andes",
    about_p1: `Soy una Product Designer Senior con un enfoque integral que conecta la experiencia de usuario (UX) con la viabilidad técnica y los objetivos de negocio. Con una sólida trayectoria transformando problemas complejos en soluciones digitales escalables, mi fuerte radica en el diseño basado en datos, la facilitación de workshops de innovación y la visión de producto 'end-to-end,'.`,
    about_p2: `A diferencia de un diseñador tradicional, integro conocimientos de desarrollo y arquitectura de producto para asegurar que cada pixel diseñado sea implementable y genere impacto real. Experta en liderar procesos de Discovery, creación de sistemas de diseño y optimización de flujos de conversión. He trabajado con equipos globales (como en Globant) ayudando a empresas a madurar su cultura de diseño y a acelerar sus ciclos de innovación.`,
    contact_title: "Contáctame",
    contact_write: "¡Escríbeme!",
    contact_linkedin: "Ver mi LinkedIn",
    contact_article: "Leer mi artículo en Medium",

    work_heading: "mis trabajos",
    work_cat1: "Salud",
    work_title1: "Market fit para Ecgo, un nuevo dispositivo de salud cardíaca",
    work_tags1: "#Investigación UX &nbsp;·&nbsp; #TechDriven &nbsp;·&nbsp; #CienciaDeDatos &nbsp;·&nbsp; #Telemedicina",
    work_cat2: "Retail",
    work_title2: "Caso de Service Design: Usuarios en el Centro de la Automatización",
    work_tags2: "#DiseñoDeServicio &nbsp;·&nbsp; #CienciaDeDatos &nbsp;·&nbsp; #Automatización",
    work_cat3: "Eventos",
    work_title3: "Internalizar un producto externo: ¿Cómo se adapta el UX/UI?",
    work_tags3: "#UI &nbsp;·&nbsp; #SistemaDeDiseno &nbsp;·&nbsp; #Colaboración",

    ecgo_cat: "Salud",
    ecgo_title: "Market fit para Ecgo, un nuevo dispositivo de salud cardíaca",
    ecgo_date: "Ecgo &nbsp;·&nbsp; Health Tech &nbsp;·&nbsp; 2018–2019",
    ecgo_tags: "#Investigación UX &nbsp;·&nbsp; #TechDriven &nbsp;·&nbsp; #CienciaDeDatos &nbsp;·&nbsp; #Telemedicina &nbsp;·&nbsp; #SaludPública &nbsp;·&nbsp; #Startup",
    ecgo_req_h: "Un dispositivo sin software.",
    ecgo_req_p: "Ecgo había desarrollado un nuevo sensor Holter cardíaco — pero sin ningún producto digital. Me incorporé para entender a pacientes, médicos y técnicos médicos en profundidad, y diseñar software desde cero que funcionara en hospitales, clínicas y hogares.",
    ecgo_disc_h: "Descubrimiento",
    ecgo_s1: "Objetivo", ecgo_s2: "Planificación", ecgo_s3: "Ejecución", ecgo_s4: "Conclusiones", ecgo_s5: "Implementación",
    ecgo_field_label: "Investigación de Campo",
    ecgo_obj_h: "01 / Objetivo",
    ecgo_obj_p: "Nuestro objetivo como equipo Solunova fue entender a todos los actores y su contexto de uso del examen Holter cardíaco en instituciones de salud pública.",
    ecgo_rq_label: "Preguntas de Investigación",
    ecgo_q1: "¿Cómo funciona el flujo tradicional del examen Holter cardíaco?",
    ecgo_q2: "¿Quiénes forman parte de este flujo y qué los caracteriza?",
    ecgo_q3: "¿Cuál es el servicio mínimo (SAL) necesario para una correcta implementación?",
    ecgo_q4: "¿Cuáles son los desafíos y oportunidades de implementar software para pacientes?",
    ecgo_plan_label: "El Plan",
    ecgo_plan_h: "02 / Planificación",
    ecgo_plan_p1: "Mi enfoque de investigación fue cualitativo, con el área comercial complementando los hallazgos con información de mercado basada en datos.",
    ecgo_plan_p2: "Este enfoque cualitativo se basó en dos actividades: sesiones de observación no participante y entrevistas no estructuradas.",
    ecgo_part_h: "Participantes",
    ecgo_part1: "4 pacientes", ecgo_part2: "2 técnicos médicos", ecgo_part3: "2 especialistas médicos cardíacos",
    ecgo_cond_h: "03 / Ejecución",
    ecgo_cond_p: "Realicé observaciones no participantes y entrevistas en profundidad con tres grupos de usuarios clave — en hospitales, clínicas y hogares de pacientes.",
    ecgo_u1_title: "Cardiólogos",
    ecgo_u1_desc: "Expertos que definen el informe del examen cardíaco — determinando la calidad de datos que los médicos necesitan para tomar decisiones clínicas.",
    ecgo_u2_title: "Técnicos Médicos",
    ecgo_u2_desc: "Clave para entender cómo viajan las señales cardíacas desde el dispositivo hasta el cardiólogo — el punto de traspaso crítico.",
    ecgo_u3_title: "Pacientes",
    ecgo_u3_desc: "Segmentados por edad, comodidad tecnológica y experiencia con el proceso Holter — el rango más amplio de necesidades en el recorrido.",
    ecgo_obs_label: "Observación de Campo",
    ecgo_obs_text: "Observación no participante realizada en sesiones de 2 horas en tres instituciones — siguiendo de primera mano el flujo completo del examen Holter.",
    ecgo_obs_loc: "Vival Medical Center &nbsp;·&nbsp; Fundación Kaplan &nbsp;·&nbsp; Hospital Cordillera Oriente",
    ecgo_conc_h: "04 / Conclusiones",
    ecgo_conc_p: "Nuestra investigación validó el potencial del dispositivo — y nos dio las bases para diseñar un tipo completamente nuevo de servicio de monitoreo cardíaco.",
    ecgo_days_unit: "Días",
    ecgo_days_desc: "Monitoreo cardíaco continuo — 4× más largo que el examen Holter tradicional.",
    ecgo_find_label: "Hallazgo Clave",
    ecgo_find_desc: "Detectó condiciones cardíacas que el examen Holter de 24 horas pasaba por alto por completo.",
    ecgo_out_label: "Resultado Clave",
    ecgo_out_desc: "Co-diseñé el informe clínico y el Acuerdo de Nivel de Servicio junto al cardiólogo y al científico de datos.",
    ecgo_impl_label: "Lo Que Construimos",
    ecgo_impl_h: "05 / Implementación",
    ecgo_impl_c1_h: "Dashboard para Cardiólogos",
    ecgo_impl_c1_p: "Agrega y registra supervisores médicos, pacientes, estudios, exámenes en tiempo real y nuevos dispositivos. Funciona para escritorio y tablet.",
    ecgo_impl_c2_h: "APP para Pacientes",
    ecgo_impl_c2_p: "Los usuarios pueden registrar síntomas y actividad durante su examen cardíaco. Los datos en tiempo real complementan el monitoreo de señal cardíaca.",
    ecgo_showcase_title: "El producto que construimos",
    ecgo_impact_h: "Impacto real",
    ecgo_impact_p: "La implementación se realizó a través de demos de laboratorio, generando exámenes médicos reales con iteraciones continuas hasta alcanzar una versión estable. El diseño fue clave — considerando la accesibilidad para pacientes y la adecuada visualización de informes para cardiólogos.",
    ecgo_still_label: "En Uso Hoy",
    ecgo_still_note: "Implementado en la Fundación Kaplan.",
    footer_back: "← Volver a trabajos",
    footer_next: "Siguiente proyecto →",
    footer_prev: "← Proyecto anterior",
    footer_back2: "Volver a trabajos",

    cen_cat: "Retail",
    cen_title: "Rediseñando la gestión de precios — usuarios en el centro de la automatización",
    cen_tags: "#DiseñoDeServicio &nbsp;·&nbsp; #TechDriven &nbsp;·&nbsp; #CienciaDeDatos &nbsp;·&nbsp; #Automatización &nbsp;·&nbsp; #GestiónDelCambio",
    cen_prob_label: "El Desafío",
    cen_prob_h: `Miles de cambios de precios. Cientos de tiendas. Tres equipos que nunca se "hablaban" entre sí.`,
    cen_prob_sub: "La complejidad no era solo técnica — era organizacional, cultural y profundamente humana.",
    cen_brief_h: "Un retailer volando a ciegas.",
    cen_brief_p: "Uno de los retailers más grandes de Latinoamérica — 500+ tiendas, miles de cambios de precios semanales — operando su gestión de precios con hojas de cálculo, WhatsApp e intuición. Mi trabajo era cambiar eso.",
    cen_role: "Mi rol: Diseñadora UX &nbsp;·&nbsp; Diseño de Servicio &nbsp;·&nbsp; Diseño de Producto",
    cen_scale_d1: "tiendas impactadas", cen_scale_d2: "tipos de usuario, necesidades distintas", cen_scale_d3: "productos diseñados desde cero",
    cen_users_h: "Para quién diseñé",
    cen_u1_name: "Planificadores",
    cen_u1_desc: "Simulan escenarios de precios y planifican cambios semanales en categorías de productos.",
    cen_u2_name: "Product Managers",
    cen_u2_desc: "Son dueños de la estrategia de producto y colecciones. Necesitan visibilidad total sobre el pipeline de precios.",
    cen_u3_name: "Asistentes de Tienda",
    cen_u3_desc: "Aplican cambios de precios en el piso en tiempo real — miles de productos, el mismo día.",
    cen_field_label: "La Base",
    cen_field_h: "Fui a las tiendas. Sin suposiciones.",
    cen_field_p: "Mientras todos debatían funcionalidades, yo estaba en las tiendas observando lo que realmente pasaba cuando llegaba un cambio de precio. La brecha entre el sistema y la realidad era más grande de lo que alguien admitía.",
    cen_sm_label: "La Metodología",
    cen_sm_h: "Cómo Mapeé el Problema",
    cen_sm_p: "Antes de diseñar una sola pantalla, mapeé cada paso, cada rol y cada traspaso en la cadena de cambios de precios. Ocho actividades. Cinco tipos de usuario. Decenas de puntos de falla. Este mapa fue la base estratégica de cada decisión que tomamos.",
    cen_sm_flow: "Product Manager &nbsp;→&nbsp; Planificador &nbsp;→&nbsp; Category Manager &nbsp;→&nbsp; Analista de Precios &nbsp;→&nbsp; Asistente de Tienda",
    cen_a1: "Monitorear Rendimiento", cen_a2: "Identificar Productos Lentos", cen_a3: "Sugerir Precio Óptimo", cen_a4: "Configurar Cambios",
    cen_a5: "Actualizar Sistema POS", cen_a6: "Notificar al Equipo de Categoría", cen_a7: "Alertar a Equipos de Tienda", cen_a8: "Etiquetar en Estante",
    cen_stats1: "5 Roles de Usuario", cen_stats2: "8 Actividades Clave", cen_stats3: "15+ Funcionalidades Diseñadas",
    cen_orc_label: "Mi Contribución Principal",
    cen_orc_h: "Mapeé cada rol, dependencia y punto de falla — y diseñé el orquestador que hizo funcionar todo el sistema.",
    cen_orc_p: "El orquestador es una herramienta semi-automatizada que rastrea el nivel de madurez del proceso de precios semanal frente a límites de tiempo predefinidos — alertando errores y manteniendo sincronizados a todos los stakeholders.",
    cen_prod_h: "Dos productos entregados*",
    cen_p1_name: "Dashboard Back-Office",
    cen_p1_desc: "Herramienta de planificación end-to-end para simular escenarios de precios, proyectar impacto en ingresos y gestionar decisiones de precios semanales.",
    cen_p1_tags: "Simulación de precios &nbsp;·&nbsp; Proyección de ingresos &nbsp;·&nbsp; Planificación semanal &nbsp;·&nbsp; Seguimiento de errores",
    cen_p2_name: "App y Dashboard de Tienda",
    cen_p2_desc: "Herramienta simple y rápida para recibir actualizaciones de precios, registrar implementación y subir foto como evidencia — todo en un lugar.",
    cen_p2_tags: "Actualizaciones en tiempo real &nbsp;·&nbsp; Foto como evidencia &nbsp;·&nbsp; Log de implementación &nbsp;·&nbsp; Dashboard de tienda",
    cen_disclaimer: "*referencia de diseño por confidencialidad",

    cve_cat: "Eventos",
    cve_title: "Internalizar un producto externo: ¿Cómo se adapta el UX/UI?",
    cve_ctx_label: "El Contexto",
    cve_ctx_h: "Studio. Adquirido,<br>pero aún sin integrar.",
    cve_ctx_p1: "La Virtual Event Platform es una empresa que ofrece soluciones de software para gestión de eventos. Studio — un producto adquirido por la Platform — es una herramienta de producción audiovisual diseñada para optimizar eventos virtuales e híbridos mediante videoconferencia.",
    cve_ctx_p2: "Mi principal desafío fue asegurar que Studio se convirtiera en una parte integral de la experiencia de la Virtual Event Platform — fluida y sin interrupciones tanto para asistentes como para organizadores.",
    cve_ch_h: "Desafíos de Studio",
    cve_ch1_name: "Sistema de Diseño Legado", cve_ch1_sub: "sin actualizaciones al sistema de diseño",
    cve_ch1_desc: "Deficiencias estructurales, estándares obsoletos e integraciones fallidas convirtieron el camino de Studio hacia la Platform en un obstáculo significativo.",
    cve_ch2_name: "Limitación Tecnológica", cve_ch2_sub: "cumplimiento de accesibilidad al momento de integración",
    cve_ch2_desc: "Los componentes Polymer no se alineaban con los estándares de comportamiento, apariencia o accesibilidad — haciendo una integración directa técnicamente imposible.",
    cve_ap_h: "¿Cómo lo abordé?",
    cve_ap1_name: "Auditar funcionalidades y componentes",
    cve_ap1_desc: "Identificar y priorizar los componentes esenciales dentro de la experiencia de Studio.",
    cve_ap2_name: "Ingeniería inversa",
    cve_ap2_desc: "Entender la construcción de los componentes — estados, estructura y comportamiento.",
    cve_ap3_name: "Diseño e iteración",
    cve_ap3_desc: "Aplicar diseño atómico para reconstruir componentes de forma consistente y accesible, alineados con los estándares de la Platform.",
    cve_ap4_name: "Publicación",
    cve_ap4_desc: "Promover la librería ante los equipos de producto e ingeniería con documentación, cheat sheets e impacto de negocio.",
    cve_aud_label: "La Auditoría",
    cve_aud_h: "1 / Auditar funcionalidades<br>y componentes",
    cve_aud_p: "No podíamos reconstruir todo — así que mapeamos lo existente, eliminamos redundancias y priorizamos por impacto.",
    cve_aud_l1: "→&nbsp; Catalogamos todos los componentes existentes",
    cve_aud_l2: "→&nbsp; Priorizamos por uso y brecha de accesibilidad",
    cve_aud_l3: "→&nbsp; Marcamos inconsistencias para reconstruir",
    cve_scope_label: "Alcance de la Auditoría",
    cve_scope_desc: "componentes mapeados y priorizados",
    cve_scope_cats: "Navegación &nbsp;·&nbsp; Formularios &nbsp;·&nbsp; Media<br>Overlays &nbsp;·&nbsp; Visualización de Datos &nbsp;·&nbsp; Utilidades",
    cve_rev_h: "2 / Ingeniería inversa",
    cve_rev_p1: "La investigación se centró en entender la construcción de los componentes de Carina. Eran muy complejos, requerían importantes recursos de diseño y desarrollo, y estaban diseñados para casos de uso que frecuentemente diferían del conjunto acotado de Studio.",
    cve_rev_p2: "Esta fase concluyó con una comprensión integral de cómo la UI, los estados, el contenido y la accesibilidad estaban estructurados dentro de los componentes de Carina.",
    cve_rev_cap: "Estados de Componente &nbsp;·&nbsp; Artefacto Real",
    cve_des_label: "El Diseño",
    cve_des_h: "3 / Diseño e iteración",
    cve_des_p: "El diseño atómico fue la base — cada componente tenía estados, comportamientos y accesibilidad definidos desde la primera iteración.",
    cve_des_l1: "→&nbsp; De átomos a templates — jerarquía completa",
    cve_des_l2: "→&nbsp; Librería unificada en Figma para todos los equipos",
    cve_des_l3: "→&nbsp; Nomenclatura acordada con los líderes de diseño",
    cve_atomic_label: "Estructura de Diseño Atómico",
    cve_out_label: "El Resultado",
    cve_pub_h: "4 / Publicación<br>y comunicación",
    cve_pub_quote: "\"El diseño fue clave — no solo los componentes, sino el lenguaje compartido para hablar de ellos.\"",
    cve_pub_body: "Promovimos la iniciativa en producto e ingeniería — creando documentación, cheat sheets y un caso de negocio para avanzar hacia la codificación real.",
    cve_del_label: "Entregables",
    cve_del_list: "· Librería de componentes intermedia<br>· Documentación de nomenclatura<br>· Guía de estándares de accesibilidad<br>· Cheat sheet de alineación con Carina",
  }
};

function applyLang(lang) {
  document.querySelectorAll('[data-i18n]').forEach(el => {
    const key = el.dataset.i18n;
    if (T[lang] && T[lang][key] !== undefined) {
      el.innerHTML = T[lang][key];
    }
  });
  const btn = document.getElementById('lang-btn');
  if (btn) btn.textContent = lang === 'en' ? 'ES' : 'EN';
  document.documentElement.lang = lang;
  localStorage.setItem('cp_lang', lang);
}

function toggleLang() {
  const current = localStorage.getItem('cp_lang') || 'en';
  applyLang(current === 'en' ? 'es' : 'en');
}

document.addEventListener('DOMContentLoaded', () => {
  applyLang(localStorage.getItem('cp_lang') || 'en');
});
